Khmer lang support
michaelwittig/node-i18n-iso-countries pull request #227
Opened 2021-02-04 14:51 UTC by davychhouk

Add Khmer language support.

Translation Reference: [Official Country Name Translation by the National Commission of Khmer Language](http://iric.gov.kh/names-of-countries-and-capitals-in-the-world-by-national-committee-of-khmer-language)

2021-02-04 14:52 UTC, davychhouk commented
Hi, @michaelwittig! 
Please have a look again. 
Thanks :)

2021-02-04 16:06 UTC, michaelwittig requested changes

2021-02-04 16:06 UTC, michaelwittig commented on langs/kh.json
> +{
could you please remove this file. this lib only contains ISO 639-1 codes.

2021-02-04 16:06 UTC, michaelwittig commented on entry-node.js
> +  require("./langs/kh.json"),
could you please remove this line. this lib only contains ISO 639-1 codes.

2021-02-04 16:06 UTC, michaelwittig commented on README.md
> +- `kh`: Khmer
could you please remove this line. this lib only contains ISO 639-1 codes.

2021-02-05 00:32 UTC, davychhouk commented
Hi @michaelwittig.

This is weird. I'm sorry. There must be sth wrong with my git thing.
In my local is clean, but after pull from the master branch, it becomes a mess.

I removed all of these again. Thanks.

2021-02-05 12:11 UTC, merged

2021-02-05 12:11 UTC, michaelwittig commented
no worries! thanks for your work!